blank_issues_enabled: false
contact_links:
  - name: TinySA-users groups.io group
    url: https://groups.io/g/TinySA-users/
    about: Please ask any questions about using the TinySA or TinySA-Saver on this mailing list.
